### PR TITLE
Added FormData object

### PR DESCRIPTION
**Pull request by GuiSim**
Added a `FormData` object that encapsulates a `byte[]` and a `String contentType`.

Currently, all `byte[]` parameters are added as an `application/octet-stream` to the request.
This new object allows users to control the content type sent as part of a `multipart/form` request.

* I've never used Lombok before so please let me know if this is okay.
* I'm also open to rename `FormData` to something you think might be more appropriate.
* I've also added `@SuppressFBWarnings` to the pom and `FormData` object since I couldn't find a way to guarantee the immutability of the `FormData` `byte[]` field.
* I also did not bump the version number. I am unsure as to what the release process is, please advise :)

Fixes https://github.com/OpenFeign/feign-form/issues/37

### CODE REVIEW

**Comment by GuiSim** [comment]
Build failed but it appears to be related to the build itself and not this PR? 
```
$ echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import
--import: command not found
The command "echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import" failed and exited with 127 during .
``` 
Looks like `$GPG_EXECUTABLE` is not defined.

**Comment by xxlabaza** [comment]
Nope, build failed because of using secure variables in .travis.yml file during regular build. You could see it log above.

It was described [here](https://docs.travis-ci.com/user/pull-requests/#Pull-Requests-and-Security-Restrictions)

I have fixed the issue and restarted your build

**Comment by GuiSim** [comment]
Thanks for the help  @xxlabaza . I have now fixed the build.

**Comment by xxlabaza** [comment]
@GuiSim, could you also add usage example, like @tjuchniewicz did with "Spring MultipartFile", at the end of README.md file? After that, I will add you as co-author

**Comment by GuiSim** [comment]
I tweaked the README which now includes an example for `File`, `byte[]` and `FormData`.

Let me know if this is sufficient!

**Comment by GuiSim** [comment]
Thanks for merging this! Will you deploy a new version with these changes?

**Comment by xxlabaza** [comment]
yep, do you have an email? Or you don't want to publish it?

**Comment by xxlabaza** [comment]
Thanks, @GuiSim for your help
New version 3.3.0 with your code was published. Will be available soon on maven central

**Comment by GuiSim** [comment]
@xxlabaza Thank you! I didn't realize that I could be deploying it myself. Appreciate it 🙌

**Pull request merged**
