### PR TITLE
OSGified feign-form jars

### PR DESCRIPTION
**Pull request by bhathiya**
Added OSGi headers to all modules in feign-form repository.

### CODE REVIEW

**Comment by bhathiya** [comment]
@xxlabaza  : Could you please merge this PR? I need this as OSGi bundles for one of our projects. What is the procedure to get a release done with this change? 

Thank you.

**Comment by xxlabaza** [comment]
done, new version is 2.2.0

**Comment by xxlabaza** [comment]
thanks a lot for your improvements

**Comment by bhathiya** [comment]
Thank you for accepting my improvement. But unfortunately, I had to drop this from my project as the license (MIT) of the dependency "lombok" is conflicting with mine (Apache 2.0). I think this problem might affect other people as well. So is there a possiblity of replacing "lombok" with some other Apache 2.0 one?

**Comment by xxlabaza** [comment]
Sorry, I am from Russia and I don't understand the words "copyright" and "license"...

But, seriously, as I can see, [accordingly this article](https://www.quora.com/Whats-the-different-between-Apache-v2-0-and-MIT-license), - you just need to add one line, like this:

"[project] includes code from foobaz, which is licensed under the MIT license:" with the original license following

**Pull request merged**
